In [1]:
# Ensure dependencies are installed when running in hosted notebooks
%pip install -r requirements.txt

ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

## Data setup

Place `BP1234-ONSET-WCOND-NUMID.csv` (or `BP1234-ONSET.csv`) here before running.

In [2]:
import pandas as pd
import numpy as np
import os
from collections.abc import Iterable
from typing import List
# --- mount (safe) ---
import urllib.request
from pathlib import Path

BASE_URL = "https://raw.githubusercontent.com/FelixZhan/AtyAN/main/"
HELPER_FILES = [
    "requirements.txt",
    "AAN-ONSET-MERGED.csv",
]

DATA_FILE_PREFERRED = "AAN-ONSET-MERGED.csv"
DATA_FILE_FALLBACK = "BP1234-ONSET.csv"

for filename in HELPER_FILES:
    dest = Path(filename)
    if dest.exists():
        print(f"{filename} already present, skipping download.")
        continue
    print(f"Downloading {filename}...")
    urllib.request.urlretrieve(f"{BASE_URL}{filename}", dest)

data_candidates = [DATA_FILE_PREFERRED, DATA_FILE_FALLBACK]
data_file = None
for cand in data_candidates:
    if Path(cand).exists():
        data_file = cand
        break

if data_file is None:
    data_file = DATA_FILE_FALLBACK
    try:
        print(f"{DATA_FILE_PREFERRED} and {DATA_FILE_FALLBACK} not found locally; attempting to download {data_file} from GitHub.")
        urllib.request.urlretrieve(f"{BASE_URL}{data_file}", data_file)
    except Exception as exc:
        raise RuntimeError(
            f"Could not find {DATA_FILE_PREFERRED} locally and download of {data_file} failed; "
            "place the dataset in this folder and re-run."
        ) from exc

print(f"Using dataset: {data_file}")

def cols_exist(df: pd.DataFrame, cols: Iterable[str]) -> List[str]:
    return [c for c in cols if c in df.columns]

Downloading requirements.txt...
Downloading AAN-ONSET-MERGED.csv...
Using dataset: AAN-ONSET-MERGED.csv

## Imports and shared setup

In [3]:
import re
import numpy as np
import pandas as pd
from pathlib import Path
import math

# Toggle BRF components on/off
RUN_BRF = True

# from imblearn.ensemble import BalancedRandomForestClassifier
from sklearn.linear_model import LogisticRegression

# Multiple imputation (MICE / IterativeImputer)
from sklearn.experimental import enable_iterative_imputer  # noqa: F401
from sklearn.impute import IterativeImputer
from sklearn.base import clone

from sklearn.model_selection import GridSearchCV, StratifiedKFold, cross_val_predict
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix
import statsmodels.api as sm

# ---- Multiple-imputation controls ----
# NOTE: MI is used for evaluation/pooling; reducing M speeds things up a lot.
MI_M = 3
MI_BASE_SEED = 42

def make_mice_imputer(*, random_state: int, sample_posterior: bool):
    return IterativeImputer(
        random_state=random_state,
        sample_posterior=sample_posterior,
        max_iter=10,
        initial_strategy="median",
        skip_complete=True,
    )

def _norm_sf(z: float) -> float:
    # Survival function for standard normal via erfc; avoids SciPy dependency.
    return 0.5 * math.erfc(z / math.sqrt(2.0))

def mi_cross_val_predict_proba(estimator, X, y, *, cv, m: int = MI_M, base_seed: int = MI_BASE_SEED, n_jobs: int = -1):
    """Average CV predicted probabilities across m multiple imputations (posterior draws)."""
    probs_m = []
    for k in range(m):
        est_k = clone(estimator)
        # If this is a Pipeline with an 'imputer' step, vary the imputer RNG per imputation.
        if hasattr(est_k, "get_params"):
            params = est_k.get_params(deep=True)
            if "imputer" in params or any(p.startswith("imputer__") for p in params):
                try:
                    est_k.set_params(
                        imputer=make_mice_imputer(random_state=base_seed + k, sample_posterior=True)
                    )
                except Exception:
                    # Fallback: set step params directly if the imputer object is already present
                    try:
                        est_k.set_params(imputer__random_state=base_seed + k, imputer__sample_posterior=True)
                    except Exception:
                        pass
        probs = cross_val_predict(est_k, X, y, cv=cv, method="predict_proba", n_jobs=n_jobs)[:, 1]
        probs_m.append(probs)
    return np.mean(np.vstack(probs_m), axis=0)

def pooled_logit_or_stats_single_feature(X: pd.DataFrame, y: pd.Series, feature: str, *, m: int = MI_M, base_seed: int = MI_BASE_SEED):
    """
    Fit statsmodels Logit on m multiply-imputed versions of a single-feature design; pool beta/SE (Rubin).
    Returns OR, 95% CI, and (normal-approx) p-value; NaNs if insufficient successful fits.
    """
    X_feat = X[[feature]].copy()
    betas = []
    vars_ = []
    for k in range(m):
        imp = make_mice_imputer(random_state=base_seed + k, sample_posterior=True)
        Xi = pd.DataFrame(imp.fit_transform(X_feat), index=X_feat.index, columns=X_feat.columns)
        X_sm = sm.add_constant(Xi, has_constant="add")
        try:
            res = sm.Logit(y, X_sm).fit(disp=False)
            beta = float(res.params.get(feature, np.nan))
            var = float(res.cov_params().loc[feature, feature]) if feature in res.params.index else np.nan
            if np.isfinite(beta) and np.isfinite(var) and var > 0:
                betas.append(beta)
                vars_.append(var)
        except Exception:
            continue
    if len(betas) < 2:
        return {"odds_ratio": np.nan, "p_value": np.nan, "ci_low": np.nan, "ci_high": np.nan}
    betas = np.asarray(betas, dtype=float)
    vars_ = np.asarray(vars_, dtype=float)
    m_eff = betas.size
    beta_bar = float(betas.mean())
    W = float(vars_.mean())
    B = float(betas.var(ddof=1))
    T = W + (1.0 + 1.0 / m_eff) * B
    se = math.sqrt(T) if T > 0 else float("nan")
    if not np.isfinite(se) or se <= 0:
        return {"odds_ratio": np.nan, "p_value": np.nan, "ci_low": np.nan, "ci_high": np.nan}
    z = beta_bar / se
    p = 2.0 * _norm_sf(abs(z))
    zcrit = 1.959963984540054
    ci_low = beta_bar - zcrit * se
    ci_high = beta_bar + zcrit * se
    return {
        "odds_ratio": float(np.exp(beta_bar)),
        "p_value": float(p),
        "ci_low": float(np.exp(ci_low)),
        "ci_high": float(np.exp(ci_high)),
    }

In [4]:
# Study condition cleaning and dummy coding (BP vs Control vs Healthy Weight)
COND_MAP = {
    "peer delivered": "BP",
    "ebody": "BP",
    "clincian delivered": "BP",
    "clinician delivered": "BP",
    "diss. (bp)": "BP",
    "exp writing": "BP",
    "control/video control": "Control",
    "healthy weight": "Healthy Weight",
}

COND_CANONICAL = {
    "BP": "BP",
    "Control": "Control",
    "Healthy Weight": "Healthy Weight",
}

def clean_and_encode_condition(df: pd.DataFrame) -> pd.DataFrame:
    """
    Clean 'study_cond' into three levels and add two dummy vectors:
      - cond_bp: 1 = BP trial condition, 0 = Control/Healthy Weight
      - cond_hw: 1 = Healthy Weight, 0 = Control/BP
    Control is the reference (0,0).
    Raises if there are missing/unmapped values.
    """
    if "study_cond" not in df.columns:
        raise KeyError("Missing 'study_cond' column; use dataset with condition labels.")

    cond_raw = df["study_cond"]
    if cond_raw.isna().any() or cond_raw.astype(str).str.strip().eq("").any():
        raise ValueError("Found missing/blank entries in 'study_cond'; expected none.")

    cond_norm = cond_raw.astype(str).str.strip().str.lower()
    cond_clean = cond_norm.map(COND_MAP)

    if cond_clean.isna().any():
        bad_vals = sorted(cond_raw.loc[cond_clean.isna()].unique())
        raise ValueError(f"Unmapped 'study_cond' values: {bad_vals}")

    df = df.copy()
    df["cond_clean"] = cond_clean.map(COND_CANONICAL).astype("category")
    df["cond_bp"] = (df["cond_clean"] == "BP").astype(int)
    df["cond_hw"] = (df["cond_clean"] == "Healthy Weight").astype(int)

    return df

In [5]:
# Helper functions and feature construction (no analysis_utils dependency)
RISK_SUFFIXES = ["tii", "bs", "dres", "socf", "dep", "intbmi"]
PRODROMAL_FEATURE_NAMES = ["BE", "CB", "WSO", "FEAR", "FAT", "LEB"]
ONSET_WEIGHT_LABEL = "mBMI"
TRUTHY_STRINGS = {"TRUE", "T", "YES", "Y", "1", "PRESENT"}
FALSY_STRINGS = {"FALSE", "F", "NO", "N", "0", "ABSENT"}

def _coerce_numeric(series: pd.Series) -> pd.Series:
    return pd.to_numeric(series, errors="coerce")

def _coerce_boolean(series: pd.Series) -> pd.Series:
    if series is None:
        return pd.Series(pd.NA, dtype="boolean")
    as_str = series.astype(str).str.strip().str.upper()
    out = pd.Series(pd.NA, index=series.index, dtype="boolean")
    out[as_str.isin(TRUTHY_STRINGS)] = True
    out[as_str.isin(FALSY_STRINGS)] = False
    numeric = pd.to_numeric(series, errors="coerce")
    out[numeric.notna()] = numeric[numeric.notna()] != 0
    return out

def _match_prefix_columns(df: pd.DataFrame, prefixes):
    cols = []
    for prefix in prefixes:
        pattern = re.compile(rf"^{re.escape(prefix)}[._-]?", flags=re.IGNORECASE)
        cols.extend([c for c in df.columns if pattern.match(c)])
    return cols

def has_cols(df: pd.DataFrame, prefixes) -> pd.Series:
    matched = _match_prefix_columns(df, prefixes)
    if not matched:
        return pd.Series(False, index=df.index)
    sub = df[matched]
    truthy = sub.apply(_coerce_boolean)
    numeric = sub.apply(_coerce_numeric)
    numeric_present = numeric.notna() & numeric.ne(0)
    return (truthy.fillna(False) | numeric_present.fillna(False)).any(axis=1)

def has_exact_cols(df: pd.DataFrame, cols) -> pd.Series:
    present = [c for c in cols if c in df.columns]
    if not present:
        return pd.Series(False, index=df.index)
    sub = df[present]
    truthy = sub.apply(_coerce_boolean)
    numeric = sub.apply(_coerce_numeric)
    numeric_present = numeric.notna() & numeric.ne(0)
    return (truthy.fillna(False) | numeric_present.fillna(False)).any(axis=1)

def engineer_wave_prodromals(work: pd.DataFrame, wave: int) -> list:
    cols = []
    base = pd.Series(np.nan, index=work.index)
    be_src = f"w{wave}ede1a"
    work[f"BE_w{wave}"] = _coerce_numeric(work.get(be_src, base))
    cols.append(f"BE_w{wave}")
    cb_cols = [c for c in [f"w{wave}ed8a", f"w{wave}ed9a", f"w{wave}ed10a", f"w{wave}ed11a"] if c in work.columns]
    if cb_cols:
        cb_block = work[cb_cols].apply(_coerce_numeric)
        work[f"CB_w{wave}"] = cb_block.max(axis=1, skipna=True)
        work.loc[cb_block.notna().sum(axis=1) == 0, f"CB_w{wave}"] = np.nan
    else:
        work[f"CB_w{wave}"] = np.nan
    cols.append(f"CB_w{wave}")
    work[f"WSO_w{wave}"] = _coerce_numeric(work.get(f"w{wave}ed15a", base))
    work[f"FEAR_w{wave}"] = _coerce_numeric(work.get(f"w{wave}ed17a", base))
    work[f"FAT_w{wave}"] = _coerce_numeric(work.get(f"w{wave}ed19a", base))
    cols.extend([f"WSO_w{wave}", f"FEAR_w{wave}", f"FAT_w{wave}"])
    mbmi_pct = _coerce_numeric(work.get(f"w{wave}mbmi_pct", base))
    work[f"LEB_w{wave}"] = np.clip(90.0 - mbmi_pct, 0, None) / 90.0
    cols.append(f"LEB_w{wave}")
    return cols

def build_predictors(df: pd.DataFrame):
    work = df.copy()
    risk_cols = []
    for suffix in RISK_SUFFIXES:
        col = f"w1{suffix}"
        if col in work.columns:
            work[col] = _coerce_numeric(work[col])
            risk_cols.append(col)
    prod_cols = engineer_wave_prodromals(work, wave=1)
    features = list(dict.fromkeys(risk_cols + prod_cols))
    cond_cols = [c for c in ["cond_bp", "cond_hw"] if c in work.columns]
    features = list(dict.fromkeys(features + cond_cols))
    return work, features

def _baseline_diagnosis_masks_00(df: pd.DataFrame):
    """Baseline diagnosis masks using ONLY .00 columns."""
    mask_an = has_exact_cols(df, ["fan.00", "pan.00"])
    mask_be = has_exact_cols(df, ["fbe.00", "pbe.00"])
    mask_bn = has_exact_cols(df, ["fbn.00", "pbn.00"])
    mask_fpu = has_exact_cols(df, ["fpu.00"])
    mask_any = mask_an | mask_be | mask_bn | mask_fpu
    return mask_an, mask_be, mask_bn, mask_fpu, mask_any

def build_onset_dataset(
    df: pd.DataFrame,
    onset_weight_label: str = ONSET_WEIGHT_LABEL,
    exclude_baseline_diagnoses: bool = False,
) -> pd.DataFrame:
    mask_w1_onset = _coerce_boolean(df.get("w1ONSET-FULL", pd.Series(np.nan, index=df.index))).fillna(False)
    mask_an, mask_be, mask_bn, mask_fpu, mask_any_baseline_dx = _baseline_diagnosis_masks_00(df)

    if exclude_baseline_diagnoses:
        subset = df.loc[~(mask_w1_onset | mask_any_baseline_dx)].copy()
    else:
        subset = df.loc[~mask_w1_onset].copy()

    onset_pattern = re.compile(rf"^w([1-6])ONSET-FULL-{re.escape(onset_weight_label)}$", re.IGNORECASE)
    onset_cols = [c for c in subset.columns if onset_pattern.match(c)]
    if not onset_cols:
        raise ValueError(f"No ONSET-FULL-{onset_weight_label} columns found in the dataset.")

    onset_block = subset[onset_cols].apply(_coerce_numeric).fillna(0)
    subset["aan_onset_anywave"] = onset_block.gt(0).any(axis=1).astype(int)
    return subset


def summarize_aim2_exclusions(
    df: pd.DataFrame,
    onset_weight_label: str = ONSET_WEIGHT_LABEL,
    exclude_baseline_diagnoses: bool = False,
    id_col: str = "id",
):
    """
    Return (flow_df, diagnosis_breakdown_df, excluded_ids_df) for Aim 2 eligibility.

    Flow reflects the exact rules applied in build_onset_dataset:
      1) Exclude baseline AAN onset (w1ONSET-FULL == 1)
      2) Optional exclusion of baseline diagnosis flags using ONLY .00 columns:
         fan.00/pan.00, fbe.00/pbe.00, fbn.00/pbn.00, fpu.00
    """
    n_total = int(len(df))

    mask_w1_onset = _coerce_boolean(df.get("w1ONSET-FULL", pd.Series(np.nan, index=df.index))).fillna(False)
    mask_an, mask_be, mask_bn, mask_fpu, mask_any_baseline_dx = _baseline_diagnosis_masks_00(df)

    n_excl_w1 = int(mask_w1_onset.sum())
    n_after_w1 = n_total - n_excl_w1

    if exclude_baseline_diagnoses:
        mask_dx_only = (~mask_w1_onset) & mask_any_baseline_dx
        n_excl_dx = int(mask_dx_only.sum())
        final_mask = ~(mask_w1_onset | mask_any_baseline_dx)
    else:
        n_excl_dx = 0
        final_mask = ~mask_w1_onset

    n_final = int(final_mask.sum())

    flow_rows = [
        {
            "step": "Initial sample",
            "n_removed": 0,
            "n_remaining": n_total,
            "reason": "All participants in source dataset",
        },
        {
            "step": "Exclude baseline AAN",
            "n_removed": n_excl_w1,
            "n_remaining": n_after_w1,
            "reason": "w1ONSET-FULL indicates baseline AAN onset",
        },
        {
            "step": "Exclude baseline AN/BE/BN/FPU (.00 only)",
            "n_removed": n_excl_dx,
            "n_remaining": n_final,
            "reason": "Any of fan.00/pan.00, fbe.00/pbe.00, fbn.00/pbn.00, fpu.00 among participants not removed in prior step",
        },
        {
            "step": "Aim 2 analytic sample",
            "n_removed": 0,
            "n_remaining": n_final,
            "reason": "Participants included in incident-onset modeling",
        },
    ]
    flow_df = pd.DataFrame(flow_rows)
    flow_df["pct_remaining_of_total"] = (flow_df["n_remaining"] / n_total * 100).round(2)

    diagnosis_breakdown_df = pd.DataFrame(
        [
            {
                "baseline_flag_group": "AN full/partial (.00: fan/pan)",
                "n_among_non_baseline_AAN": int((~mask_w1_onset & mask_an).sum()),
            },
            {
                "baseline_flag_group": "BED full/partial (.00: fbe/pbe)",
                "n_among_non_baseline_AAN": int((~mask_w1_onset & mask_be).sum()),
            },
            {
                "baseline_flag_group": "BN full/partial (.00: fbn/pbn)",
                "n_among_non_baseline_AAN": int((~mask_w1_onset & mask_bn).sum()),
            },
            {
                "baseline_flag_group": "PU full (.00: fpu)",
                "n_among_non_baseline_AAN": int((~mask_w1_onset & mask_fpu).sum()),
            },
            {
                "baseline_flag_group": "Any of the above (.00, unique)",
                "n_among_non_baseline_AAN": int((~mask_w1_onset & mask_any_baseline_dx).sum()),
            },
        ]
    )

    if id_col in df.columns:
        id_series = df[id_col]
    else:
        id_series = pd.Series(df.index, index=df.index, name="index")

    excluded_parts = [
        pd.DataFrame(
            {
                "participant_id": id_series.loc[mask_w1_onset].to_numpy(),
                "reason": "baseline_AAN_w1ONSET_FULL",
            }
        )
    ]

    if exclude_baseline_diagnoses:
        excluded_parts.extend(
            [
                pd.DataFrame(
                    {
                        "participant_id": id_series.loc[mask_an].to_numpy(),
                        "reason": "baseline_AN_full_or_partial_fan00_pan00",
                    }
                ),
                pd.DataFrame(
                    {
                        "participant_id": id_series.loc[mask_be].to_numpy(),
                        "reason": "baseline_BED_full_or_partial_fbe00_pbe00",
                    }
                ),
                pd.DataFrame(
                    {
                        "participant_id": id_series.loc[mask_bn].to_numpy(),
                        "reason": "baseline_BN_full_or_partial_fbn00_pbn00",
                    }
                ),
                pd.DataFrame(
                    {
                        "participant_id": id_series.loc[mask_fpu].to_numpy(),
                        "reason": "baseline_PU_full_fpu00",
                    }
                ),
            ]
        )

    excluded_ids_df = pd.concat(excluded_parts, ignore_index=True)
    excluded_ids_df = excluded_ids_df.drop_duplicates().sort_values(["reason", "participant_id"]).reset_index(drop=True)

    return flow_df, diagnosis_breakdown_df, excluded_ids_df

In [6]:
# Load once (reuse the data_file chosen in setup)
raw_df = pd.read_csv(Path(data_file), low_memory=False)
print(f"Loaded dataset: {data_file}")

# Clean and encode study condition dummies
df_with_cond = clean_and_encode_condition(raw_df)

# Build predictors and outcome
feature_df, base_features = build_predictors(df_with_cond)

# Aim 2 cohort rule flag:
# - Always exclude baseline AAN onset (w1ONSET-FULL)
# - Optionally exclude baseline diagnosis flags (.00 only):
#   fan.00/pan.00, fbe.00/pbe.00, fbn.00/pbn.00, and fpu.00
# Default is NO extra diagnosis exclusion (False).
EXCLUDE_BASELINE_DIAGNOSES = False

aim2_flow, aim2_dx_breakdown, aim2_excluded_ids = summarize_aim2_exclusions(
    feature_df,
    onset_weight_label=ONSET_WEIGHT_LABEL,
    exclude_baseline_diagnoses=EXCLUDE_BASELINE_DIAGNOSES,
    id_col="id",
)
print("Aim 2 eligibility flow:")
display(aim2_flow)

print("Baseline diagnosis breakdown among participants without baseline AAN:")
display(aim2_dx_breakdown)

exclusion_flow_path = Path("aim2_exclusion_flow.csv")
exclusion_breakdown_path = Path("aim2_exclusion_breakdown.csv")
excluded_ids_path = Path("aim2_excluded_participants.csv")
aim2_flow.to_csv(exclusion_flow_path, index=False)
aim2_dx_breakdown.to_csv(exclusion_breakdown_path, index=False)
aim2_excluded_ids.to_csv(excluded_ids_path, index=False)
print(f"Saved exclusion flow: {exclusion_flow_path}")
print(f"Saved exclusion breakdown: {exclusion_breakdown_path}")
print(f"Saved participant-level exclusion list: {excluded_ids_path}")


dataset = build_onset_dataset(
    feature_df,
    onset_weight_label=ONSET_WEIGHT_LABEL,
    exclude_baseline_diagnoses=EXCLUDE_BASELINE_DIAGNOSES,
)
predictor_cols = [c for c in base_features if c in dataset.columns and not c.endswith("-persistence")]

# Ensure condition dummies are evaluated individually in univariate models
for cond_col in ["cond_bp", "cond_hw"]:
    if cond_col in dataset.columns and cond_col not in predictor_cols:
        predictor_cols.append(cond_col)

X = dataset[predictor_cols]
y = dataset["aan_onset_anywave"]
print("Predictors:", predictor_cols)
print("Class balance:", y.value_counts().to_dict())
print(f"Design matrix shape: {X.shape}")
print(f"Aim 2 analytic N: {len(dataset):,}")

Loaded dataset: AAN-ONSET-MERGED.csv
Aim 2 eligibility flow:

,step,n_removed,n_remaining,reason,pct_remaining_of_total
0,Initial sample,0,1952,All participants in source dataset,100.00
1,Exclude baseline AAN,34,1918,w1ONSET-FULL indicates baseline AAN onset,98.26
2,Exclude baseline AN/BE/BN/FPU (.00 only),0,1918,"Any of fan.00/pan.00, fbe.00/pbe.00, fbn.00/pb...",98.26
3,Aim 2 analytic sample,0,1918,Participants included in incident-onset modeling,98.26

Baseline diagnosis breakdown among participants without baseline AAN:

               baseline_flag_group  n_among_non_baseline_AAN
0   AN full/partial (.00: fan/pan)                         9
1  BED full/partial (.00: fbe/pbe)                        66
2   BN full/partial (.00: fbn/pbn)                       113
3               PU full (.00: fpu)                        19
4   Any of the above (.00, unique)                       207

Saved exclusion flow: aim2_exclusion_flow.csv
Saved exclusion breakdown: aim2_exclusion_breakdown.csv
Saved participant-level exclusion list: aim2_excluded_participants.csv
Predictors: ['w1tii', 'w1bs', 'w1dres', 'w1socf', 'w1dep', 'w1intbmi', 'BE_w1', 'CB_w1', 'WSO_w1', 'FEAR_w1', 'FAT_w1', 'LEB_w1', 'cond_bp', 'cond_hw']
Class balance: {0: 1859, 1: 59}
Design matrix shape: (1918, 14)
Aim 2 analytic N: 1,918

In [7]:
# from matplotlib import pyplot as plt
# import re

# # Plot 1: Age at FIRST onset wave (w1ONSET-FULL, then w2–w6ONSET-FULL-mBMI)
# if "raw_df" not in globals():
#     raise RuntimeError("raw_df not found — run the data loading cell(s) first.")
# if "_coerce_boolean" not in globals():
#     raise RuntimeError("_coerce_boolean not found — run the feature/helper setup cells first.")
# if "ONSET_WEIGHT_LABEL" not in globals():
#     raise RuntimeError("ONSET_WEIGHT_LABEL not found — run the feature/helper setup cells first.")

# src_df = raw_df.copy()  # use the full sample (do NOT use `dataset`, which excludes w1 onsets)

# def _find_col_case_insensitive(df: pd.DataFrame, exact_name: str):
#     target = exact_name.lower()
#     for c in df.columns:
#         if c.lower() == target:
#             return c
#     return None

# def _find_first_matching(df: pd.DataFrame, pattern: str):
#     rx = re.compile(pattern, flags=re.IGNORECASE)
#     for c in df.columns:
#         if rx.match(c):
#             return c
#     return None

# def _wave_onset_flag(df: pd.DataFrame, wave: int, *, onset_weight_label: str = ONSET_WEIGHT_LABEL) -> pd.Series:
#     """Boolean onset flag for a given wave."""
#     if wave == 1:
#         c = _find_col_case_insensitive(df, "w1ONSET-FULL")
#         if c is None:
#             c = _find_first_matching(df, r"^w1ONSET-FULL$")
#         if c is None:
#             raise KeyError("Could not find w1ONSET-FULL column in the dataset.")
#         return _coerce_boolean(df[c]).fillna(False)
#     else:
#         # Prefer exact w{wave}ONSET-FULL-{label}, but fall back to any w{wave}ONSET-FULL-* if needed
#         c = _find_first_matching(df, rf"^w{wave}ONSET-FULL-{re.escape(onset_weight_label)}$")
#         if c is None:
#             c = _find_first_matching(df, rf"^w{wave}ONSET-FULL-")
#         if c is None:
#             # If the dataset truly doesn't contain that wave's onset flag, treat as no onset for that wave.
#             return pd.Series(False, index=df.index)
#         vals = pd.to_numeric(df[c], errors="coerce").fillna(0)
#         return vals.gt(0)

# def _best_wave_age_col(df: pd.DataFrame, wave: int):
#     """Pick the most plausible wave-specific age column for a given wave."""
#     # Strong preference for exact w{wave}age
#     exact = _find_col_case_insensitive(df, f"w{wave}age")
#     if exact is not None:
#         return exact
#     # Next: anything like w{wave}...age (but avoid onset age labels if present)
#     rx = re.compile(rf"w{wave}.*age", flags=re.IGNORECASE)
#     candidates = [c for c in df.columns if rx.match(c)]
#     if not candidates:
#         return None
#     # Choose the candidate with the most numeric data
#     best_col = None
#     best_non_na = -1
#     for c in candidates:
#         ser = pd.to_numeric(df[c], errors="coerce")
#         nn = int(ser.notna().sum())
#         if nn > best_non_na:
#             best_non_na = nn
#             best_col = c
#     return best_col

# # Compute first onset wave per participant
# waves = list(range(1, 7))
# flag_mat = np.column_stack([_wave_onset_flag(src_df, w).to_numpy(dtype=bool) for w in waves])
# any_onset = flag_mat.any(axis=1)
# first_idx = np.argmax(flag_mat, axis=1)  # 0 if all-false; fixed by any_onset mask below
# first_wave = np.where(any_onset, first_idx + 1, np.nan)

# # Map first onset wave to that wave's age
# age_at_first_onset = pd.Series(np.nan, index=src_df.index, dtype=float)
# age_col_by_wave = {w: _best_wave_age_col(src_df, w) for w in waves}
# for w in waves:
#     age_col = age_col_by_wave.get(w)
#     if age_col is None:
#         continue
#     wave_age = pd.to_numeric(src_df[age_col], errors="coerce")
#     mask = first_wave == w
#     age_at_first_onset.loc[mask] = wave_age.loc[mask]

# # Gate: only participants with any onset flag
# ages = age_at_first_onset.loc[any_onset]
# ages = ages[(ages >= 12) & (ages <= 20)].dropna()

# if len(ages) == 0:
#     raise ValueError(
#         "No usable ages found for first-onset wave (after gating to onset participants and filtering to 12–20). "
#         "Check that wave-specific age columns exist (e.g., w1age..w6age) and contain numeric values."
#     )

# plt.figure(figsize=(8, 4))
# bins = np.arange(12, 21 + 1) - 0.5
# plt.hist(ages, bins=bins, edgecolor="black")
# plt.xticks(range(12, 21))
# plt.title("Age at first ED onset (first flagged wave; ages 12–20)")
# plt.xlabel("Age")
# plt.ylabel("Count")
# plt.tight_layout()
# plt.show()

# # Plot 2: simple equation
# plt.figure(figsize=(6, 2))
# plt.axis("off")
# plt.text(0.5, 0.5, r"Current models assume $\beta = \mathrm{constant}$",
#          ha="center", va="center", fontsize=14)
# plt.tight_layout()
# plt.show()

In [8]:
# Missingness report for Wave 1 variables

if "dataset" in globals():
    df_src = dataset
elif "feature_df" in globals():
    df_src = feature_df
elif "raw_df" in globals():
    df_src = raw_df
else:
    raise RuntimeError("No dataframe found. Run the data setup/loading cells first.")

# Wave 1 columns: starts with w1... OR engineered ..._w1
wave1_cols = [c for c in df_src.columns if c.lower().startswith("w1") or c.lower().endswith("_w1")]

if len(wave1_cols) == 0:
    raise ValueError("No Wave 1 variables were found in the selected dataframe.")

n = len(df_src)
missing_report = pd.DataFrame(
    {
        "variable": wave1_cols,
        "n_missing": [int(df_src[c].isna().sum()) for c in wave1_cols],
    }
)
missing_report["pct_missing"] = (missing_report["n_missing"] / n * 100).round(2)
missing_report = missing_report.sort_values(["pct_missing", "n_missing"], ascending=False).reset_index(drop=True)

print(f"Rows: {n:,} | Wave 1 variables: {len(wave1_cols)}")
display(missing_report)

print("Top 15 most-missing Wave 1 variables:")
display(missing_report.head(15))

Rows: 1,918 | Wave 1 variables: 567

         variable  n_missing  pct_missing
0        w1sclchg       1918       100.00
1         w1obese       1918       100.00
2         w1es22b       1894        98.75
3           w1es9       1887        98.38
4          w1es13       1887        98.38
..            ...        ...          ...
562    w1bmi_used          0         0.00
563  w1ONSET-FULL          0         0.00
564  w1HEALTHY-WL          0         0.00
565         CB_w1          0         0.00
566        WSO_w1          0         0.00

[567 rows x 3 columns]

Top 15 most-missing Wave 1 variables:

    variable  n_missing  pct_missing
0   w1sclchg       1918       100.00
1    w1obese       1918       100.00
2    w1es22b       1894        98.75
3      w1es9       1887        98.38
4     w1es13       1887        98.38
5     w1es14       1887        98.38
6      w1es7       1886        98.33
7      w1es8       1886        98.33
8     w1es10       1886        98.33
9     w1es11       1886        98.33
10    w1es12       1886        98.33
11     w1es6       1856        96.77
12  w1psytxa       1855        96.72
13  w1chng7a       1797        93.69
14    w1es21       1770        92.28

In [9]:
# Missingness summary for requested predictors across waves 1-6

# Pick the most analysis-ready dataframe available
if "dataset" in globals():
    df_src = dataset
elif "feature_df" in globals():
    df_src = feature_df
elif "df_with_cond" in globals():
    df_src = df_with_cond
elif "raw_df" in globals():
    df_src = raw_df
else:
    raise RuntimeError("No dataframe found. Run setup/loading cells first.")

# Use existing globals if present; otherwise defaults
risk_suffixes = globals().get("RISK_SUFFIXES", ["tii", "bs", "dres", "socf", "dep", "intbmi"])
prodromal_features = globals().get("PRODROMAL_FEATURE_NAMES", ["BE", "CB", "WSO", "FEAR", "FAT", "LEB"])
waves = range(1, 7)

n_total = len(df_src)
col_map = {c.lower(): c for c in df_src.columns}

def first_existing(candidates):
    for c in candidates:
        real = col_map.get(c.lower())
        if real is not None:
            return real
    return None

rows = []

# Risk suffixes: expected form w{wave}{suffix}
for wave in waves:
    for sfx in risk_suffixes:
        target = f"w{wave}{sfx}"
        col = first_existing([target])
        n_missing = int(df_src[col].isna().sum()) if col is not None else n_total
        rows.append(
            {
                "group": "risk",
                "feature": sfx,
                "wave": wave,
                "expected_name": target,
                "matched_column": col,
                "found": col is not None,
                "n_missing": n_missing,
                "pct_missing": round(100 * n_missing / n_total, 2),
            }
        )

# Prodromals: expected engineered form {NAME}_w{wave}
for wave in waves:
    for feat in prodromal_features:
        target = f"{feat}_w{wave}"
        col = first_existing([target, f"{feat.lower()}_w{wave}"])
        n_missing = int(df_src[col].isna().sum()) if col is not None else n_total
        rows.append(
            {
                "group": "prodromal",
                "feature": feat,
                "wave": wave,
                "expected_name": target,
                "matched_column": col,
                "found": col is not None,
                "n_missing": n_missing,
                "pct_missing": round(100 * n_missing / n_total, 2),
            }
        )

missing_w1_w6 = pd.DataFrame(rows).sort_values(["group", "feature", "wave"]).reset_index(drop=True)

print(f"Rows: {n_total:,}")
print("Detailed missingness (w1-w6):")
display(missing_w1_w6)

print("Percent-missing matrix (risk):")
display(
    missing_w1_w6.loc[missing_w1_w6["group"] == "risk"]
    .pivot(index="feature", columns="wave", values="pct_missing")
    .sort_index()
)

print("Percent-missing matrix (prodromal):")
display(
    missing_w1_w6.loc[missing_w1_w6["group"] == "prodromal"]
    .pivot(index="feature", columns="wave", values="pct_missing")
    .sort_index()
)

Rows: 1,918
Detailed missingness (w1-w6):

,group,feature,wave,expected_name,matched_column,found,n_missing,pct_missing
0,prodromal,BE,1,BE_w1,BE_w1,True,3,0.16
1,prodromal,BE,2,BE_w2,None,False,1918,100.00
2,prodromal,BE,3,BE_w3,None,False,1918,100.00
3,prodromal,BE,4,BE_w4,None,False,1918,100.00
4,prodromal,BE,5,BE_w5,None,False,1918,100.00
...,...,...,...,...,...,...,...,...
67,risk,tii,2,w2tii,w2tii,True,75,3.91
68,risk,tii,3,w3tii,w3tii,True,588,30.66
69,risk,tii,4,w4tii,w4tii,True,150,7.82
70,risk,tii,5,w5tii,w5tii,True,203,10.58
71,risk,tii,6,w6tii,w6tii,True,307,16.01

Percent-missing matrix (risk):

wave        1      2      3      4      5      6
feature
bs       0.05   3.96  30.76   7.82  10.38  16.11
dep      0.52   4.59  30.76  10.17  14.18  20.33
dres     0.16   4.07  30.92   7.87  10.84  16.11
intbmi   1.72   5.63  13.56  12.20  21.95  52.09
socf     0.05  43.90  54.17  16.63   9.85  16.01
tii      0.10   3.91  30.66   7.82  10.58  16.01

Percent-missing matrix (prodromal):

wave        1      2      3      4      5      6
feature
BE       0.16  100.0  100.0  100.0  100.0  100.0
CB       0.00  100.0  100.0  100.0  100.0  100.0
FAT      0.16  100.0  100.0  100.0  100.0  100.0
FEAR     0.05  100.0  100.0  100.0  100.0  100.0
LEB      1.72  100.0  100.0  100.0  100.0  100.0
WSO      0.00  100.0  100.0  100.0  100.0  100.0

In [10]:
# Complete-case missingness for ALL wave-based predictors (w1 to w6)

# Pick the most analysis-ready dataframe available
if "dataset" in globals():
    df_src = dataset
elif "feature_df" in globals():
    df_src = feature_df
elif "raw_df" in globals():
    df_src = raw_df
else:
    raise RuntimeError("No dataframe found. Run the setup/loading cells first.")

# Define wave-based predictor columns:
# - include columns starting with w1..w6
# - exclude ONSET columns (typically outcomes, not predictors)
wave_pred_cols = [
    c for c in df_src.columns
    if re.match(r"^w[1-6]", str(c), flags=re.IGNORECASE)
    and "onset" not in str(c).lower()
]

if len(wave_pred_cols) == 0:
    raise ValueError("No predictor columns found for waves w1..w6 after filtering.")

# Complete-case status across ALL selected predictors
cc_mask = df_src[wave_pred_cols].notna().all(axis=1)

n_total = len(df_src)
n_complete = int(cc_mask.sum())
n_incomplete = n_total - n_complete

complete_case_summary = pd.DataFrame(
    [{
        "n_rows": n_total,
        "n_predictor_cols_w1_to_w6": len(wave_pred_cols),
        "n_complete_cases": n_complete,
        "pct_complete_cases": round(100 * n_complete / n_total, 2),
        "n_incomplete_cases": n_incomplete,
        "pct_incomplete_cases": round(100 * n_incomplete / n_total, 2),
    }]
)

# Variable-level missingness (for context)
var_missing = pd.DataFrame({
    "variable": wave_pred_cols,
    "n_missing": [int(df_src[c].isna().sum()) for c in wave_pred_cols],
})
var_missing["pct_missing"] = (var_missing["n_missing"] / n_total * 100).round(2)
var_missing = var_missing.sort_values(["pct_missing", "n_missing"], ascending=False).reset_index(drop=True)

print("Complete-case summary across ALL w1–w6 predictors:")
display(complete_case_summary)

print("Top 20 most-missing predictor variables (w1–w6):")
display(var_missing.head(20))

Complete-case summary across ALL w1–w6 predictors:

,n_rows,n_predictor_cols_w1_to_w6,n_complete_cases,pct_complete_cases,n_incomplete_cases,pct_incomplete_cases
0,1918,2281,0,0.0,1918,100.0

Top 20 most-missing predictor variables (w1–w6):

    variable  n_missing  pct_missing
0   w1sclchg       1918       100.00
1   w5sclchg       1918       100.00
2     w6ed20       1918       100.00
3   w6sclchg       1918       100.00
4    w1obese       1918       100.00
5      w2es7       1903        99.22
6      w2es8       1903        99.22
7      w2es9       1903        99.22
8     w2es10       1903        99.22
9     w2es11       1903        99.22
10    w2es12       1903        99.22
11    w2es13       1903        99.22
12    w2es14       1903        99.22
13   w1es22b       1894        98.75
14    w3con1       1890        98.54
15    w3con2       1890        98.54
16    w3con3       1890        98.54
17    w3con4       1890        98.54
18    w3con5       1890        98.54
19    w3con6       1890        98.54

In [11]:
feature = "w1tii"  # change to the feature you want
X_feat = pd.to_numeric(X[feature], errors="coerce").replace([np.inf, -np.inf], np.nan)
valid = X_feat.notna()
X_sm = sm.add_constant(X_feat[valid], has_constant="add")
# IMPORTANT: don't overwrite the global `y` used by later cells
y_valid = y.loc[valid]
res = sm.Logit(y_valid, X_sm).fit(disp=False)
beta = float(res.params[feature])
beta

0.762596971384022

## Univariate predictor grid searches

Evaluate each predictor alone with Balanced RF and class-weighted Logistic (AUROC via stratified CV); thresholds will be tuned later for balanced accuracy.

In [12]:
# Speed knobs: keep the workflow the same but drastically reduce compute.
N_SPLITS = 3  # was 5
cv = StratifiedKFold(n_splits=N_SPLITS, shuffle=True, random_state=42)

# Respect the global toggle if it exists
RUN_BRF = bool(globals().get("RUN_BRF", False))

# Optional: pick what GridSearchCV refits on
# - "roc_auc": maximize AUROC (threshold-free)
# - "feasible_bal_acc": maximize best balanced accuracy subject to sens/spec constraints
REFIT_METRIC = "roc_auc"

# Sens/spec feasibility constraints for tuning-time scorer
MIN_SENS_GS = 0.55
MIN_SPEC_GS = 0.55
THRESHOLDS_GS = np.linspace(0.01, 0.99, 99)

# tqdm progress bar (optional)
try:
    from tqdm.auto import tqdm
except Exception:  # pragma: no cover
    tqdm = lambda x, **kwargs: x  # fallback: no progress bar

from sklearn.metrics import make_scorer
import inspect

def _best_feasible_bal_acc_from_proba(y_true, y_proba, *, min_sens: float, min_spec: float, thresholds):
    """Return best balanced accuracy among thresholds meeting sens/spec constraints.

    IMPORTANT: Must return a finite float (not NaN), otherwise GridSearchCV emits
    'non-finite test scores' warnings and can break refit behavior.
    """
    y_true = np.asarray(y_true).astype(int)
    y_proba = np.asarray(y_proba)
    if y_proba.ndim == 2 and y_proba.shape[1] >= 2:
        y_proba = y_proba[:, 1]
    best = np.nan
    for thr in thresholds:
        y_pred = (y_proba >= thr).astype(int)
        tn, fp, fn, tp = confusion_matrix(y_true, y_pred, labels=[0, 1]).ravel()
        sens = tp / (tp + fn) if (tp + fn) > 0 else np.nan
        spec = tn / (tn + fp) if (tn + fp) > 0 else np.nan
        if not (np.isfinite(sens) and np.isfinite(spec)):
            continue
        if (sens < min_sens) or (spec < min_spec):
            continue
        bal_acc = 0.5 * (sens + spec)
        if (not np.isfinite(best)) or (bal_acc > best):
            best = bal_acc
    # If nothing is feasible, score it as 0.0 (worst) instead of NaN.
    return float(best) if np.isfinite(best) else 0.0

def feasible_bal_acc_score(y_true, y_proba, *, min_sens: float, min_spec: float, thresholds):
    """Custom scorer: best feasible balanced accuracy over thresholds."""
    return _best_feasible_bal_acc_from_proba(
        y_true, y_proba, min_sens=min_sens, min_spec=min_spec, thresholds=thresholds
    )

def safe_roc_auc_score(y_true, y_proba):
    """ROC AUC that never returns NaN (returns 0.5 if undefined)."""
    from sklearn.metrics import roc_auc_score
    y_proba = np.asarray(y_proba)
    if y_proba.ndim == 2 and y_proba.shape[1] >= 2:
        y_proba = y_proba[:, 1]
    try:
        return float(roc_auc_score(y_true, y_proba))
    except Exception:
        # e.g., if a fold has only one class in y_true
        return 0.5

# scikit-learn changed scorer API: use response_method when available; fall back to needs_proba on older versions.
if "response_method" in inspect.signature(make_scorer).parameters:
    feasible_bal_acc_scorer = make_scorer(
        feasible_bal_acc_score,
        response_method="predict_proba",
        greater_is_better=True,
        min_sens=MIN_SENS_GS,
        min_spec=MIN_SPEC_GS,
        thresholds=THRESHOLDS_GS,
    )
    roc_auc_scorer = make_scorer(
        safe_roc_auc_score,
        response_method="predict_proba",
        greater_is_better=True,
    )
else:
    feasible_bal_acc_scorer = make_scorer(
        feasible_bal_acc_score,
        needs_proba=True,
        greater_is_better=True,
        min_sens=MIN_SENS_GS,
        min_spec=MIN_SPEC_GS,
        thresholds=THRESHOLDS_GS,
    )
    roc_auc_scorer = make_scorer(
        safe_roc_auc_score,
        needs_proba=True,
        greater_is_better=True,
    )

# --- Logistic (always runs) ---
# Use deterministic IterativeImputer during model selection; MI averaging is used for evaluation later.
log_pipe = Pipeline(
    [
        ("imputer", make_mice_imputer(random_state=42, sample_posterior=False)),
        ("scaler", StandardScaler()),
        ("model", LogisticRegression(max_iter=3000, class_weight="balanced")),
    ]
)

# Bigger grid than before (20 combos) while staying manageable for univariate runs.
# liblinear supports both L1 and L2 for binary classification.
log_grid = {
    "model__C": [1e-4, 3e-4, 1e-3, 3e-3, 1e-2, 3e-2, 1e-1, 3e-1, 1.0, 3.0],
    "model__penalty": ["l1", "l2"],
    "model__solver": ["liblinear"],
}

# --- Balanced RF ---
if RUN_BRF:
    from imblearn.ensemble import BalancedRandomForestClassifier
    brf_pipe = Pipeline(
        [
            ("imputer", make_mice_imputer(random_state=42, sample_posterior=False)),
            ("model", BalancedRandomForestClassifier(random_state=42, n_jobs=-1)),
        ]
)

    # Keep BRF grid modest; univariate BRF can still get expensive.
    brf_grid = {
        "model__n_estimators": [200, 400],
        "model__max_depth": [None, 5],
        "model__min_samples_leaf": [1, 2],
        "model__max_features": ["sqrt"],
    }

scoring = {"roc_auc": roc_auc_scorer, "feasible_bal_acc": feasible_bal_acc_scorer}

results = []
log_searches = []
brf_searches = []

# Respect optional feature limiting if present in the kernel
features_to_run = list(globals().get("features_to_run", predictor_cols))

# Safety: ensure X and y have identical rows before GridSearchCV
if (len(X) != len(y)) or (hasattr(y, "index") and not X.index.equals(y.index)):
    common_index = X.index.intersection(y.index)
    X = X.loc[common_index].copy()
    y = y.loc[common_index].copy()
    print(f"Aligned X and y to a common index: {X.shape[0]} rows")

for feature in tqdm(features_to_run, desc="Univariate grid searches", unit="feature"):
    X_feat = X[[feature]]

    log_search = GridSearchCV(
        log_pipe,
        param_grid=log_grid,
        cv=cv,
        scoring=scoring,
        refit=REFIT_METRIC,
        n_jobs=-1,
        error_score="raise",
    )
    log_search.fit(X_feat, y)
    log_searches.append((feature, log_search))

    bi = log_search.best_index_
    results.append(
        {
            "feature": feature,
            "model": "logistic",
            "best_auc": float(log_search.cv_results_["mean_test_roc_auc"][bi]),
            "best_feasible_bal_acc": float(log_search.cv_results_["mean_test_feasible_bal_acc"][bi]),
            "best_params": log_search.best_params_,
        }
)

    if RUN_BRF:
        brf_search = GridSearchCV(
            brf_pipe,
            param_grid=brf_grid,
            cv=cv,
            scoring=scoring,
            refit=REFIT_METRIC,
            n_jobs=-1,
            error_score="raise",
        )
        brf_search.fit(X_feat, y)
        brf_searches.append((feature, brf_search))

        bi = brf_search.best_index_
        results.append(
            {
                "feature": feature,
                "model": "balanced_rf",
                "best_auc": float(brf_search.cv_results_["mean_test_roc_auc"][bi]),
                "best_feasible_bal_acc": float(brf_search.cv_results_["mean_test_feasible_bal_acc"][bi]),
                "best_params": brf_search.best_params_,
            }
)

results_df = pd.DataFrame(results).sort_values(["best_auc"], ascending=False)

print("Top univariate predictors (by AUROC):")
display(results_df.head(20))

# Pick best-by-AUROC searches (independent of refit metric)
best_log_feature, best_log_search = max(
    log_searches,
    key=lambda t: t[1].cv_results_["mean_test_roc_auc"][t[1].best_index_],
)
best_log_auc = best_log_search.cv_results_["mean_test_roc_auc"][best_log_search.best_index_]
print(f"Best logistic feature: {best_log_feature} (AUROC {best_log_auc:.3f})")

if RUN_BRF and brf_searches:
    best_brf_feature, best_brf_search = max(
        brf_searches,
        key=lambda t: t[1].cv_results_["mean_test_roc_auc"][t[1].best_index_],
)
    best_brf_auc = best_brf_search.cv_results_["mean_test_roc_auc"][best_brf_search.best_index_]
    print(f"Best balanced RF feature: {best_brf_feature} (AUROC {best_brf_auc:.3f})")
else:
    best_brf_feature, best_brf_search = None, None
    print("Balanced RF disabled (RUN_BRF=False).")

Univariate grid searches:   0%|          | 0/14 [00:00<?, ?feature/s]

Top univariate predictors (by AUROC):

,feature,model,best_auc,best_feasible_bal_acc,best_params
8,w1dep,logistic,0.702525,0.616171,"{'model__C': 0.0001, 'model__penalty': 'l2', '..."
16,WSO_w1,logistic,0.700222,0.000000,"{'model__C': 0.0001, 'model__penalty': 'l2', '..."
17,WSO_w1,balanced_rf,0.699854,0.217138,"{'model__max_depth': None, 'model__max_feature..."
21,FAT_w1,balanced_rf,0.699162,0.656608,"{'model__max_depth': None, 'model__max_feature..."
3,w1bs,balanced_rf,0.698975,0.722483,"{'model__max_depth': None, 'model__max_feature..."
20,FAT_w1,logistic,0.698318,0.000000,"{'model__C': 0.0001, 'model__penalty': 'l2', '..."
18,FEAR_w1,logistic,0.697995,0.237861,"{'model__C': 0.0001, 'model__penalty': 'l2', '..."
19,FEAR_w1,balanced_rf,0.692468,0.669545,"{'model__max_depth': None, 'model__max_feature..."
2,w1bs,logistic,0.680633,0.000000,"{'model__C': 0.0001, 'model__penalty': 'l2', '..."
4,w1dres,logistic,0.676819,0.000000,"{'model__C': 0.0001, 'model__penalty': 'l2', '..."
9,w1dep,balanced_rf,0.646029,0.424080,"{'model__max_depth': 5, 'model__max_features':..."
5,w1dres,balanced_rf,0.642461,0.630977,"{'model__max_depth': 5, 'model__max_features':..."
10,w1intbmi,logistic,0.625587,0.427745,"{'model__C': 0.0001, 'model__penalty': 'l2', '..."
22,LEB_w1,logistic,0.610180,0.000000,"{'model__C': 0.0001, 'model__penalty': 'l2', '..."
23,LEB_w1,balanced_rf,0.606543,0.000000,"{'model__max_depth': None, 'model__max_feature..."
1,w1tii,balanced_rf,0.605595,0.611957,"{'model__max_depth': None, 'model__max_feature..."
14,CB_w1,logistic,0.604659,0.000000,"{'model__C': 0.0001, 'model__penalty': 'l2', '..."
0,w1tii,logistic,0.598934,0.000000,"{'model__C': 0.0001, 'model__penalty': 'l2', '..."
6,w1socf,logistic,0.594796,0.000000,"{'model__C': 0.0001, 'model__penalty': 'l2', '..."
11,w1intbmi,balanced_rf,0.593669,0.609550,"{'model__max_depth': None, 'model__max_feature..."

Best logistic feature: w1dep (AUROC 0.703)
Best balanced RF feature: WSO_w1 (AUROC 0.700)

## Recreate best estimators, store for inference, and compute logistic ORs/p-values

In [13]:
from copy import deepcopy

# Respect the global toggle if it exists
RUN_BRF = bool(globals().get("RUN_BRF", False))

# Make failure mode explicit (avoids confusing KeyError: 'best_auc')
if "log_searches" not in globals() or len(log_searches) == 0:
    raise RuntimeError(
        "log_searches is empty — run Cell 10 (Univariate predictor grid searches) first."
    )

# Persist fitted best estimators for later inference/SHAP
log_best_estimators = {feat: search.best_estimator_ for feat, search in log_searches}
brf_best_estimators = {feat: search.best_estimator_ for feat, search in brf_searches} if RUN_BRF else {}

rows = []
for feature, search in log_searches:
    stats = pooled_logit_or_stats_single_feature(X, y, feature, m=MI_M, base_seed=MI_BASE_SEED)
    rows.append(
        {
            "feature": feature,
            "model": "logistic",
            "best_auc": search.best_score_,
            "best_params": search.best_params_,
            **stats,
        }
    )

# BRF summary rows currently disabled
if RUN_BRF:
    for feature, search in brf_searches:
        rows.append(
            {
                "feature": feature,
                "model": "balanced_rf",
                "best_auc": search.best_score_,
                "best_params": search.best_params_,
                "odds_ratio": np.nan,
                "p_value": np.nan,
                "ci_low": np.nan,
                "ci_high": np.nan,
            }
        )

if len(rows) == 0:
    raise RuntimeError("No model rows were created; check Cell 10 outputs and feature list.")

best_models_summary = pd.DataFrame(rows).sort_values("best_auc", ascending=False)

def bh_fdr(pvals: pd.Series) -> pd.Series:
    """Benjamini–Hochberg FDR (BH-FDR) adjusted p-values.

    - Preserves index; returns NaN for NaN inputs.
    - Does not require statsmodels.
    """
    p = pd.to_numeric(pvals, errors="coerce")
    q = pd.Series(np.nan, index=p.index, dtype=float)
    mask = p.notna()
    pv = p.loc[mask].to_numpy(dtype=float)
    m = int(pv.size)
    if m == 0:
        return q
    order = np.argsort(pv)
    pv_sorted = pv[order]
    ranks = np.arange(1, m + 1, dtype=float)
    q_sorted = pv_sorted * m / ranks
    q_sorted = np.minimum.accumulate(q_sorted[::-1])[::-1]
    q_sorted = np.clip(q_sorted, 0.0, 1.0)
    q_unsorted = np.empty_like(q_sorted)
    q_unsorted[order] = q_sorted
    q.loc[mask] = q_unsorted
    return q

# Add BH-FDR corrected p-values for the univariate logistic tests
if {"model", "p_value"}.issubset(best_models_summary.columns):
    log_mask = best_models_summary["model"] == "logistic"
    if bool(log_mask.any()):
        p_raw = pd.to_numeric(best_models_summary.loc[log_mask, "p_value"], errors="coerce")
        best_models_summary.loc[log_mask, "p_value_bh"] = bh_fdr(p_raw)
        # Keep the BH column right after the raw p-value column (if present)
        if "p_value" in best_models_summary.columns and "p_value_bh" in best_models_summary.columns:
            cols = list(best_models_summary.columns)
            cols.remove("p_value_bh")
            cols.insert(cols.index("p_value") + 1, "p_value_bh")
            best_models_summary = best_models_summary[cols]

print("Stored fitted estimators for inference:")
print(f"  Logistic: {len(log_best_estimators)} features")
if RUN_BRF:
    print(f"  Balanced RF: {len(brf_best_estimators)} features")

print("Top 5 by AUROC (logistic):")
display(best_models_summary[best_models_summary["model"] == "logistic"].head(5))
if RUN_BRF:
    print("Top 5 by AUROC (balanced RF):")
    display(best_models_summary[best_models_summary["model"] == "balanced_rf"].head(5))

print("Full summary with odds ratios (logistic only):")
display(best_models_summary)

Stored fitted estimators for inference:
  Logistic: 14 features
  Balanced RF: 14 features
Top 5 by AUROC (logistic):

,feature,model,best_auc,best_params,odds_ratio,p_value,p_value_bh,ci_low,ci_high
4,w1dep,logistic,0.702525,"{'model__C': 0.0001, 'model__penalty': 'l2', '...",1.817964,1.111841e-07,7.782888e-07,1.457887,2.266975
8,WSO_w1,logistic,0.700222,"{'model__C': 0.0001, 'model__penalty': 'l2', '...",1.813587,7.367206e-07,2.578522e-06,1.432844,2.295502
10,FAT_w1,logistic,0.698318,"{'model__C': 0.0001, 'model__penalty': 'l2', '...",1.389555,4.015776e-07,1.874029e-06,1.223554,1.578078
9,FEAR_w1,logistic,0.697995,"{'model__C': 0.0001, 'model__penalty': 'l2', '...",1.337954,1.011083e-07,7.782888e-07,1.201987,1.489302
1,w1bs,logistic,0.680633,"{'model__C': 0.0001, 'model__penalty': 'l2', '...",2.605641,1.939771e-06,5.431358e-06,1.756485,3.865314

Top 5 by AUROC (balanced RF):

,feature,model,best_auc,best_params,odds_ratio,p_value,p_value_bh,ci_low,ci_high
22,WSO_w1,balanced_rf,0.699854,"{'model__max_depth': None, 'model__max_feature...",NaN,NaN,NaN,NaN,NaN
24,FAT_w1,balanced_rf,0.699162,"{'model__max_depth': None, 'model__max_feature...",NaN,NaN,NaN,NaN,NaN
15,w1bs,balanced_rf,0.698975,"{'model__max_depth': None, 'model__max_feature...",NaN,NaN,NaN,NaN,NaN
23,FEAR_w1,balanced_rf,0.692468,"{'model__max_depth': None, 'model__max_feature...",NaN,NaN,NaN,NaN,NaN
18,w1dep,balanced_rf,0.646029,"{'model__max_depth': 5, 'model__max_features':...",NaN,NaN,NaN,NaN,NaN

Full summary with odds ratios (logistic only):

,feature,model,best_auc,best_params,odds_ratio,p_value,p_value_bh,ci_low,ci_high
4,w1dep,logistic,0.702525,"{'model__C': 0.0001, 'model__penalty': 'l2', '...",1.817964e+00,1.111841e-07,7.782888e-07,1.457887e+00,2.266975
8,WSO_w1,logistic,0.700222,"{'model__C': 0.0001, 'model__penalty': 'l2', '...",1.813587e+00,7.367206e-07,2.578522e-06,1.432844e+00,2.295502
22,WSO_w1,balanced_rf,0.699854,"{'model__max_depth': None, 'model__max_feature...",NaN,NaN,NaN,NaN,NaN
24,FAT_w1,balanced_rf,0.699162,"{'model__max_depth': None, 'model__max_feature...",NaN,NaN,NaN,NaN,NaN
15,w1bs,balanced_rf,0.698975,"{'model__max_depth': None, 'model__max_feature...",NaN,NaN,NaN,NaN,NaN
10,FAT_w1,logistic,0.698318,"{'model__C': 0.0001, 'model__penalty': 'l2', '...",1.389555e+00,4.015776e-07,1.874029e-06,1.223554e+00,1.578078
9,FEAR_w1,logistic,0.697995,"{'model__C': 0.0001, 'model__penalty': 'l2', '...",1.337954e+00,1.011083e-07,7.782888e-07,1.201987e+00,1.489302
23,FEAR_w1,balanced_rf,0.692468,"{'model__max_depth': None, 'model__max_feature...",NaN,NaN,NaN,NaN,NaN
1,w1bs,logistic,0.680633,"{'model__C': 0.0001, 'model__penalty': 'l2', '...",2.605641e+00,1.939771e-06,5.431358e-06,1.756485e+00,3.865314
2,w1dres,logistic,0.676819,"{'model__C': 0.0001, 'model__penalty': 'l2', '...",2.045423e+00,9.495099e-06,2.215523e-05,1.490159e+00,2.807591
18,w1dep,balanced_rf,0.646029,"{'model__max_depth': 5, 'model__max_features':...",NaN,NaN,NaN,NaN,NaN
16,w1dres,balanced_rf,0.642461,"{'model__max_depth': 5, 'model__max_features':...",NaN,NaN,NaN,NaN,NaN
5,w1intbmi,logistic,0.625587,"{'model__C': 0.0001, 'model__penalty': 'l2', '...",1.059641e+00,4.080320e-03,7.140559e-03,1.018565e+00,1.102373
11,LEB_w1,logistic,0.610180,"{'model__C': 0.0001, 'model__penalty': 'l2', '...",6.462782e-12,1.318354e-02,1.845696e-02,9.179604e-21,0.004550
25,LEB_w1,balanced_rf,0.606543,"{'model__max_depth': None, 'model__max_feature...",NaN,NaN,NaN,NaN,NaN
14,w1tii,balanced_rf,0.605595,"{'model__max_depth': None, 'model__max_feature...",NaN,NaN,NaN,NaN,NaN
7,CB_w1,logistic,0.604659,"{'model__C': 0.0001, 'model__penalty': 'l2', '...",1.031903e+00,1.596837e-01,1.862976e-01,9.877069e-01,1.078077
0,w1tii,logistic,0.598934,"{'model__C': 0.0001, 'model__penalty': 'l2', '...",2.145481e+00,7.882730e-03,1.226202e-02,1.221734e+00,3.767666
3,w1socf,logistic,0.594796,"{'model__C': 0.0001, 'model__penalty': 'l2', '...",2.086073e+00,2.028090e-03,4.056179e-03,1.307749e+00,3.327628
19,w1intbmi,balanced_rf,0.593669,"{'model__max_depth': None, 'model__max_feature...",NaN,NaN,NaN,NaN,NaN
17,w1socf,balanced_rf,0.579646,"{'model__max_depth': None, 'model__max_feature...",NaN,NaN,NaN,NaN,NaN
26,cond_bp,balanced_rf,0.571843,"{'model__max_depth': None, 'model__max_feature...",NaN,NaN,NaN,NaN,NaN
12,cond_bp,logistic,0.571843,"{'model__C': 0.0001, 'model__penalty': 'l2', '...",5.570860e-01,2.810017e-02,3.576386e-02,3.304776e-01,0.939080
6,BE_w1,logistic,0.539401,"{'model__C': 0.0001, 'model__penalty': 'l2', '...",1.043270e+00,2.596771e-01,2.796523e-01,9.691865e-01,1.123017
21,CB_w1,balanced_rf,0.510164,"{'model__max_depth': 5, 'model__max_features':...",NaN,NaN,NaN,NaN,NaN
13,cond_hw,logistic,0.500000,"{'model__C': 0.0001, 'model__penalty': 'l1', '...",1.531272e+00,3.727447e-01,3.727447e-01,5.999890e-01,3.908061
27,cond_hw,balanced_rf,0.480900,"{'model__max_depth': None, 'model__max_feature...",NaN,NaN,NaN,NaN,NaN
20,BE_w1,balanced_rf,0.472082,"{'model__max_depth': None, 'model__max_feature...",NaN,NaN,NaN,NaN,NaN

In [14]:
# Logistic-only summary (rounded to 0.001) before threshold selection
if "best_models_summary" not in globals():
    raise RuntimeError("best_models_summary not found; run the grid-search and summary cells first.")

# Compute accuracy/sensitivity/specificity at default 0.5 threshold for each logistic model
# using multiple-imputation-averaged CV probabilities.

def _compute_metrics(feature: str):
    est = log_best_estimators.get(feature)
    if est is None:
        return {"accuracy": np.nan, "sensitivity": np.nan, "specificity": np.nan}
    probs = mi_cross_val_predict_proba(est, X[[feature]], y, cv=cv, m=MI_M, base_seed=MI_BASE_SEED, n_jobs=-1)
    preds = (probs >= 0.5).astype(int)
    tn, fp, fn, tp = confusion_matrix(y, preds, labels=[0, 1]).ravel()
    sens = tp / (tp + fn) if (tp + fn) > 0 else np.nan
    spec = tn / (tn + fp) if (tn + fp) > 0 else np.nan
    acc = (tp + tn) / (tp + tn + fp + fn) if (tp + tn + fp + fn) > 0 else np.nan
    return {"accuracy": acc, "sensitivity": sens, "specificity": spec}

def bh_fdr(pvals: pd.Series) -> pd.Series:
    """Benjamini–Hochberg FDR (BH-FDR) adjusted p-values.

    - Preserves index; returns NaN for NaN inputs.
    - Does not require statsmodels.
    """
    p = pd.to_numeric(pvals, errors="coerce")
    q = pd.Series(np.nan, index=p.index, dtype=float)
    mask = p.notna()
    pv = p.loc[mask].to_numpy(dtype=float)
    m = int(pv.size)
    if m == 0:
        return q
    order = np.argsort(pv)
    pv_sorted = pv[order]
    ranks = np.arange(1, m + 1, dtype=float)
    q_sorted = pv_sorted * m / ranks
    q_sorted = np.minimum.accumulate(q_sorted[::-1])[::-1]
    q_sorted = np.clip(q_sorted, 0.0, 1.0)
    q_unsorted = np.empty_like(q_sorted)
    q_unsorted[order] = q_sorted
    q.loc[mask] = q_unsorted
    return q

log_only = best_models_summary[best_models_summary["model"] == "logistic"].copy()
metric_rows = [_compute_metrics(f) for f in log_only["feature"]]
log_only = pd.concat([log_only.reset_index(drop=True), pd.DataFrame(metric_rows)], axis=1)

# --- BH-FDR correction across univariate tests (logistic only) ---
if "p_value" in log_only.columns:
    p_raw = pd.to_numeric(log_only["p_value"], errors="coerce")
    p_bh = bh_fdr(p_raw)
    insert_at = int(log_only.columns.get_loc("p_value")) + 1
    if "p_value_bh" in log_only.columns:
        log_only["p_value_bh"] = p_bh
    else:
        log_only.insert(insert_at, "p_value_bh", p_bh)

# --- Derive SE from reported 95% CI (log-odds scale) ---
# If CI is for OR: OR = exp(beta), CI = exp(beta ± z*SE_beta)  =>
# SE_beta = (log(ci_high) - log(ci_low)) / (2*z)
if {"ci_low", "ci_high"}.issubset(log_only.columns):
    z = 1.959963984540054  # ~N(0,1) 97.5% quantile for 95% CI
    ci_low = pd.to_numeric(log_only["ci_low"], errors="coerce")
    ci_high = pd.to_numeric(log_only["ci_high"], errors="coerce")
    ok = (ci_low > 0) & (ci_high > 0) & ci_low.notna() & ci_high.notna()
    se_beta = pd.Series(np.nan, index=log_only.index, dtype=float)
    se_beta.loc[ok] = (np.log(ci_high.loc[ok]) - np.log(ci_low.loc[ok])) / (2.0 * z)
    log_only["se_beta"] = se_beta
    # Delta-method SE for OR: Var(exp(beta)) ≈ exp(beta)^2 Var(beta)  => SE_or ≈ OR * SE_beta
    or_vals = pd.to_numeric(log_only.get("odds_ratio"), errors="coerce")
    log_only["se_or"] = or_vals * log_only["se_beta"]

rounded_cols = {
    c: 3
    for c in [
        "best_auc",
        "odds_ratio",
        "se_beta",
        "se_or",
        "p_value",
        "p_value_bh",
        "ci_low",
        "ci_high",
        "accuracy",
        "sensitivity",
        "specificity",
    ]
    if c in log_only
}
log_only = log_only.round(rounded_cols)

def _format_p(v):
    if pd.isna(v):
        return np.nan
    try:
        v = float(v)
    except Exception:
        return v
    return "<0.001" if v < 0.001 else f"{v:.3f}"

for col in ["p_value", "p_value_bh"]:
    if col in log_only.columns:
        log_only[col] = log_only[col].apply(_format_p)

if "model" in log_only.columns:
    log_only = log_only.drop(columns=["model"])

print(
    "Logistic models (AUROC, pooled MI ORs/p-values + BH-FDR q-values, MI-averaged CV metrics at 0.5; p<0.001 shown as <0.001):"
 )
display(log_only)

Logistic models (AUROC, pooled MI ORs/p-values + BH-FDR q-values, MI-averaged CV metrics at 0.5; p<0.001 shown as <0.001):

,feature,best_auc,best_params,odds_ratio,p_value,p_value_bh,ci_low,ci_high,accuracy,sensitivity,specificity,se_beta,se_or
0,w1dep,0.703,"{'model__C': 0.0001, 'model__penalty': 'l2', '...",1.818,<0.001,<0.001,1.458,2.267,0.590,0.644,0.588,0.113,0.205
1,WSO_w1,0.700,"{'model__C': 0.0001, 'model__penalty': 'l2', '...",1.814,<0.001,<0.001,1.433,2.296,0.448,0.864,0.435,0.120,0.218
2,FAT_w1,0.698,"{'model__C': 0.0001, 'model__penalty': 'l2', '...",1.390,<0.001,<0.001,1.224,1.578,0.532,0.814,0.523,0.065,0.090
3,FEAR_w1,0.698,"{'model__C': 0.0001, 'model__penalty': 'l2', '...",1.338,<0.001,<0.001,1.202,1.489,0.628,0.729,0.625,0.055,0.073
4,w1bs,0.681,"{'model__C': 0.0001, 'model__penalty': 'l2', '...",2.606,<0.001,<0.001,1.756,3.865,0.493,0.797,0.484,0.201,0.524
5,w1dres,0.677,"{'model__C': 0.0001, 'model__penalty': 'l2', '...",2.045,<0.001,<0.001,1.490,2.808,0.508,0.814,0.498,0.162,0.331
6,w1intbmi,0.626,"{'model__C': 0.0001, 'model__penalty': 'l2', '...",1.060,0.004,0.007,1.019,1.102,0.633,0.593,0.635,0.020,0.021
7,LEB_w1,0.610,"{'model__C': 0.0001, 'model__penalty': 'l2', '...",0.000,0.013,0.018,0.000,0.005,0.247,0.966,0.224,10.394,0.000
8,CB_w1,0.605,"{'model__C': 0.0001, 'model__penalty': 'l2', '...",1.032,0.160,0.186,0.988,1.078,0.729,0.407,0.739,0.022,0.023
9,w1tii,0.599,"{'model__C': 0.0001, 'model__penalty': 'l2', '...",2.145,0.008,0.012,1.222,3.768,0.490,0.627,0.486,0.287,0.616
10,w1socf,0.595,"{'model__C': 0.0001, 'model__penalty': 'l2', '...",2.086,0.002,0.004,1.308,3.328,0.525,0.610,0.522,0.238,0.497
11,cond_bp,0.572,"{'model__C': 0.0001, 'model__penalty': 'l2', '...",0.557,0.028,0.036,0.330,0.939,0.585,0.559,0.586,0.266,0.148
12,BE_w1,0.539,"{'model__C': 0.0001, 'model__penalty': 'l2', '...",1.043,0.260,0.280,0.969,1.123,0.807,0.254,0.824,0.038,0.039
13,cond_hw,0.500,"{'model__C': 0.0001, 'model__penalty': 'l1', '...",1.531,0.373,0.373,0.600,3.908,0.031,1.000,0.000,0.478,0.732

## Threshold selection (balanced accuracy, constrained)

Choose thresholds that maximize balanced accuracy **subject to** sensitivity and specificity both being at least 0.55.
This targets your "good AUROC, but also sens/spec >= 0.55" goal without changing the AUROC-based model ranking.

In [15]:
# Constrained threshold selection: require sensitivity and specificity >= 0.55
MIN_SENS = 0.55
MIN_SPEC = 0.55

# Finer grid than before; cheap once probabilities are computed.
thresholds = np.linspace(0.01, 0.99, 99)

# Respect the global toggle if it exists
RUN_BRF = bool(globals().get("RUN_BRF", False))

def evaluate_thresholds(name: str, search, X_subset, *, min_sens: float = MIN_SENS, min_spec: float = MIN_SPEC):
    """
    Pick threshold maximizing balanced accuracy, subject to sens/spec constraints.
    Uses MI-averaged CV probabilities for stability with missingness.
    """
    # MI-averaged CV probabilities
    probs = mi_cross_val_predict_proba(
        search.best_estimator_,
        X_subset,
        y,
        cv=cv,
        m=MI_M,
        base_seed=MI_BASE_SEED,
        n_jobs=-1,
    )
    rows = []
    for thr in thresholds:
        preds = (probs >= thr).astype(int)
        tn, fp, fn, tp = confusion_matrix(y, preds, labels=[0, 1]).ravel()
        sens = tp / (tp + fn) if (tp + fn) > 0 else np.nan
        spec = tn / (tn + fp) if (tn + fp) > 0 else np.nan
        acc = (tp + tn) / (tp + tn + fp + fn) if (tp + tn + fp + fn) > 0 else np.nan
        bal_acc = (sens + spec) / 2 if np.isfinite(sens) and np.isfinite(spec) else np.nan
        rows.append(
            {
                "threshold": float(thr),
                "sensitivity": float(sens) if np.isfinite(sens) else np.nan,
                "specificity": float(spec) if np.isfinite(spec) else np.nan,
                "accuracy": float(acc) if np.isfinite(acc) else np.nan,
                "balanced_accuracy": float(bal_acc) if np.isfinite(bal_acc) else np.nan,
            }
        )
    results = pd.DataFrame(rows)
    results["feasible"] = (results["sensitivity"] >= min_sens) & (results["specificity"] >= min_spec)

    if results["balanced_accuracy"].notna().sum() == 0:
        print(f"{name}: no valid balanced accuracy values.")
        display(results.head(10))
        return None

    feasible = results.loc[results["feasible"]].copy()
    if len(feasible) > 0:
        best = feasible.sort_values(
            ["balanced_accuracy", "accuracy", "sensitivity", "specificity"],
            ascending=[False, False, False, False],
        ).iloc[0]
        print(
            f"{name}: best *feasible* threshold {best.threshold:.2f} "
            f"(bal_acc {best.balanced_accuracy:.3f}, sens {best.sensitivity:.3f}, "
            f"spec {best.specificity:.3f}, acc {best.accuracy:.3f}; AUROC {search.best_score_:.3f})"
        )
        print(f"Feasible thresholds (sens>={min_sens:.2f}, spec>={min_spec:.2f}) — top 10 by balanced accuracy:")
        display(feasible.sort_values("balanced_accuracy", ascending=False).head(10))
        return best
    else:
        # No threshold satisfies constraints; show best unconstrained as a diagnostic.
        best = results.sort_values(
            ["balanced_accuracy", "accuracy", "sensitivity", "specificity"],
            ascending=[False, False, False, False],
        ).iloc[0]
        print(
            f"{name}: no thresholds meet sens>={min_sens:.2f} and spec>={min_spec:.2f}. "
            f"Best unconstrained threshold {best.threshold:.2f} "
            f"(bal_acc {best.balanced_accuracy:.3f}, sens {best.sensitivity:.3f}, "
            f"spec {best.specificity:.3f}, acc {best.accuracy:.3f}; AUROC {search.best_score_:.3f})"
        )
        display(results.sort_values("balanced_accuracy", ascending=False).head(10))
        return None

# BRF threshold selection
if RUN_BRF and best_brf_search is not None and best_brf_feature is not None:
    brf_best_threshold = evaluate_thresholds("Balanced RF", best_brf_search, X[[best_brf_feature]])
else:
    brf_best_threshold = None

# Logistic threshold selection
log_best_threshold = evaluate_thresholds("Logistic", best_log_search, X[[best_log_feature]])

Balanced RF: best *feasible* threshold 0.53 (bal_acc 0.636, sens 0.610, spec 0.661, acc 0.660; AUROC 0.700)
Feasible thresholds (sens>=0.55, spec>=0.55) — top 10 by balanced accuracy:

    threshold  sensitivity  specificity  accuracy  balanced_accuracy  feasible
52       0.53     0.610169     0.661108  0.659541           0.635639      True

Logistic: best *feasible* threshold 0.50 (bal_acc 0.616, sens 0.644, spec 0.588, acc 0.590; AUROC 0.703)
Feasible thresholds (sens>=0.55, spec>=0.55) — top 10 by balanced accuracy:

    threshold  sensitivity  specificity  accuracy  balanced_accuracy  feasible
49        0.5     0.644068     0.588488  0.590198           0.616278      True

## Logistic odds ratios and p-values

Fit an unpenalized logistic model on the best logistic feature to report ORs and p-values.

In [16]:
# Pooled multiple-imputation odds ratio and p-value for the best logistic feature
stats = pooled_logit_or_stats_single_feature(X, y, best_log_feature, m=MI_M, base_seed=MI_BASE_SEED)
print(f"Best logistic feature: {best_log_feature}")
print(f"Odds ratio: {stats['odds_ratio']:.3f} (95% CI: {stats['ci_low']:.3f}, {stats['ci_high']:.3f})")
print(f"p-value: {stats['p_value']:.3g}")

Best logistic feature: w1dep
Odds ratio: 1.818 (95% CI: 1.458, 2.267)
p-value: 1.11e-07